{% set name = "sumtypes" %}
{% set version = "0.1a6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sumtypes-{{ version }}.tar.gz
  sha256: 1a6ff095e06a1885f340ddab803e0f38e3f9bed81f9090164ca9682e04e96b43

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - attrs
    - python >={{ python_min }}

test:
  imports:
    - sumtypes
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/radix/sumtypes/
  summary: Algebraic types for Python (notably providing Sum Types, aka Tagged Unions)
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kevinheavey
